### PR TITLE
Algorithims Added

### PR DESCRIPTION
**Pull request by tushar8049**

### CODE REVIEW

**Comment by tushar8049** [comment]
@Arvindiyer Done!!!

**Comment by Arvindiyer** [comment]
@tushar8049  I still see lot of label1 files .Solve that.
- DO keep an eye on constraints in problem statement and in 3 problem do check the encryption logic once,

**Comment by tushar8049** [comment]
@Arvindiyer I have deleted the multiple label1 files

I think there is an error with the output that you have mentioned in the problem statement 3.

**I/P:** 120          **O/P:** 121,4

Here the output 121 is not correct. For the same input the computer is showing output as **O/P: 131,3**
Please check and let me know.

**Comment by Arvindiyer** [comment]
@tushar8049  I have updated the problem statement DO check it.

**Pull request merged**
